spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update

server.port=3000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
file.upload.base-path=/home/coder/app/server/uploads

# OTP settings
otp.expiry.minutes=5
otp.resend.cooldown.seconds=30
otp.max.attempts=5

# ✅ Real Email mode
otp.demo.mode=false

# ✅ Gmail SMTP (Email OTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=charandevireddy17@gmail.com
spring.mail.password=xekq zufj oysq nvdp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000